channels:
- conda-forge
dependencies:
- python=3.10.7
- pip<=22.2.2
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - numpy==1.26.2
  - packaging==23.2
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.11.4
name: mlflow-env
